name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.21.x]
        os: [linux]
        arch: [amd64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      # - name: Build
      #   env:
      #     GOOS: ${{ matrix.os }}
      #     GOARCH: ${{ matrix.arch }}
      #   run: go build -o wise ./cmd/main.go

      - name: Test
        run: go test -v ./pkg/...
